### ISSUE TITLE
Support minimal test scenario on main branch

### ISSUE THREAD

**Issue by HerbertJordan** [Fantom-foundation/Norma#259]
To establish a functional base level, a minimal scenario should be established to be reliably supported by the `main` branch of Norma. The scenario could look like this:
```
name: Sanity Check for Main
duration: 60

# In the network there is a single application producing constant load.
applications:
  - name: load
    type: counter
    start: 10          # start time
    end: 50            # termination time
    rate:
      constant: 20    # Tx/s
```

This test case shall from now on also server as a CI smoke test for code contributions (see #257).
