### ISSUE TITLE
Support joining and leaving validators

### ISSUE THREAD

**Issue by HerbertJordan** [Fantom-foundation/Norma#262]

**Comment by kjezek** [comment]
I guess after removal of a lot of unfishned and perhpas buggy code, it seems to work at the moment. 

It ried this scenario:


```
# The network scenario to exercise.
nodes:
  # We include three additional non-validator nodes for the full duration.
  - name: A
    instances: 2
    features: [validator]

  - name: B
    start: 120          # start time
    end: 200            # termination time
    instances: 2
    features: [validator]

  - name: C
    start: 240          # start time
    end: 300            # termination time
    instances: 3
    features: [validator]

# In the network there is a single application producing constant load.
applications:
  - name: load
    type: counter
    start: 10          # start time
    end: 500            # termination time
    users: 20          # number of users using the app
    rate:
      constant: 20     # Tx/s

```
and it was producing load while validators were added and removed
