### ISSUE TITLE
Broken connection when running single genesis validator and registering new validators by SFC

### ISSUE THREAD

**Issue by matejmode** [Fantom-foundation/Norma#303]
When network is running with just a single genesis validator, then it doesn't want to allow connection of new validators registered by SFC and network halts.

Network stops processing transactions ~20 seconds after validator-A gets added.
```
name: Network Halt

duration: 6000

# The number of genesis validator nodes in the network.
num_validators: 1

# The network scenario to exercise.
nodes:
  # Change the number of nodes during the scenario.
  - name: validator-A
    start: 20
    instances: 1
    client:
      type: validator


# In the network there is a single application producing constant load.
applications:
  - name: load
    type: counter
    start: 10           # start time
    end: 5700            # termination time
    users: 20           # number of users / accounts generating txs
    rate:
      constant: 100     # Tx/s

```

Setting genesis number of validators to 2 (or more) fixes this problem.
